### ISSUE TITLE
Add profile picture of complete faculty staff

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#10]
Add a folder containing profile picture of complete faculty staff

The final folder should look like [this](https://github.com/GOVINDDIXIT/IIITA-Student-App/tree/master/faculty/photos)

**Comment by amitmeena24** [comment]
I want to claim this issue.

**Comment by Retarded-Ape** [comment]
I want to claim this issue.
