### ISSUE TITLE
Add getsetfoss site to the navigation drawer

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#11]
Add getsetfoss site to the navigation drawer menu 

To know more about Navigation drawer Check [this](https://www.journaldev.com/9958/android-navigation-drawer-example-tutorial)

- *Multiple people can work at the same time, first one to get the PR merged will be awarded the points*

**Comment by Retarded-Ape** [comment]
I want to fix this issue.
