### ISSUE TITLE
Add loader / Shimmer

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#122]
Show loader while fetching data in main feed and archives section
Use this: https://github.com/nntuyen/mkloader with Golden Sharingan

**Comment by GOVINDDIXIT** [comment]
@refactor-droidyy

**Comment by GOVINDDIXIT** [comment]
@refactor-droidyy any update?

**Comment by yk1ax** [comment]
@GOVINDDIXIT can I try resolving this issue ?
