### ISSUE TITLE
Better Option for Entry through verifyText in VerifyActivity

### ISSUE THREAD

**Issue by yk1ax** [GOVINDDIXIT/IIITL-Student-APP#126]
On clicking on verifyText we get the keyboard popup with new line action button we can change that to 'Done' and add the Submit button functionality
In the current version the user has to press back and then press the Submit button

**Comment by yk1ax** [comment]
@GOVINDDIXIT I can add this small feature

**Comment by GOVINDDIXIT** [comment]
Okay @yk1ax Go Ahead 👍
