### ISSUE TITLE
Show visibility of password not visible

### ISSUE THREAD

**Issue by refactor-droidyy** [GOVINDDIXIT/IIITL-Student-APP#136]
While authenticating through email and entering the password, the password visibility button is not visible.

**Comment by refactor-droidyy** [comment]
@yk1ax

**Comment by yk1ax** [comment]
> @yk1ax

I'm on it

**Comment by yk1ax** [comment]
I tried multiple methods and also tried searching on the net but none if them worked and at last this method king of worked with just one problem

in the .setTheme() function I used a custom theme that I defined in styles.xml
<style name="FirebaseUITheme" parent="FirebaseUI">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowBackground">@android:color/black</item>
        <item name="android:textColor">@android:color/black</item>
        <item name="android:editTextColor">@color/colorAccent</item>
        <item name="passwordToggleTint">@color/colorAccent</item>
</style>

The only problem here was that
<item name="passwordToggleTint">@color/colorAccent</item> showed no change and so the passwordToggleButton remained in its default color
![rps20200519_180027](https://user-images.githubusercontent.com/54735451/82326725-ea4cd900-99fa-11ea-9c95-f510a435e079.jpg)
![rps20200519_180010](https://user-images.githubusercontent.com/54735451/82326734-ecaf3300-99fa-11ea-9ec1-09955107b8e2.jpg)

**Comment by yk1ax** [comment]
@GOVINDDIXIT @refactor-droidyy I need some guidance on this one.
