### ISSUE TITLE
Change is Timetable UI 

### ISSUE THREAD

**Issue by refactor-droidyy** [GOVINDDIXIT/IIITL-Student-APP#138]
Make some changes in the timetable Activity as UI doesn't match with the app UI flow.

**Comment by refactor-droidyy** [comment]
@yk1ax

**Comment by yk1ax** [comment]
> @yk1ax

I'm on it

**Comment by yk1ax** [comment]
@refactor-droidyy Before working on this feature I wanted to try something. I tried replacing all the fragments of the five days with just one fragment instead and it was working without any problem exactly like before. If doing that is a good practice then I can implement that and after that I can work on it's UI. If it's okay then I would create a new issue for that and then make a PR for it successively.

**Comment by yk1ax** [comment]
> Make some changes in the timetable Activity as UI doesn't match with the app UI flow.

And about UI, Is this one alright ? Or do I need to make more changes ?
![20200516_023947](https://user-images.githubusercontent.com/54735451/82096649-fbf26000-971e-11ea-9a4e-09b5fe6d21a2.jpg)

**Comment by refactor-droidyy** [comment]
@yk1ax the text inside the recyclerView showing the day heading is not required as from the tab bar selected it can be easily understood. Add some background for the RecyclerView that matches the UI flow of the app as it looks a little odd.
@GOVINDDIXIT your view any suggestions?

**Comment by GOVINDDIXIT** [comment]
@yk1ax Yes, remove day heading and increase font size of the content

**Comment by yk1ax** [comment]
@refactor-droidyy @GOVINDDIXIT I tried these two backgrounds by using gradient 
![20200522_100302](https://user-images.githubusercontent.com/54735451/82631816-1c855300-9c14-11ea-87c3-fe3a99011aa6.jpg)
![20200522_100345](https://user-images.githubusercontent.com/54735451/82631837-28711500-9c14-11ea-8649-934037e04ce4.jpg)

Is either one of them good to go or should I use some icon in place of gradient background ?

**Comment by GOVINDDIXIT** [comment]
@yk1ax Don't use gradient. Set background to light yellow and make text complete black

**Comment by yk1ax** [comment]
@GOVINDDIXIT I've made the changes. Let me know if the following looks good
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/54735451/82646262-e656cc00-9c31-11ea-9240-32ecf466ab78.gif)

**Comment by GOVINDDIXIT** [comment]
Looks good

**Comment by refactor-droidyy** [comment]
@yk1ax LGTM 👍
