### ISSUE TITLE
Update the Faculty Section

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#207]
Refer [here](https://iiitl.ac.in/index.php/faculty/)

**Comment by yk1ax** [comment]
I'm on it :+1:

**Comment by yk1ax** [comment]
@GOVINDDIXIT  Many of the faculties don't have section of research areas in their pages so should I leave the 'ResearchAreas' field empty in the json file for those faculties ?

**Comment by GOVINDDIXIT** [comment]
If research area is absent put their field/subject they taught else leave empty

**Comment by yk1ax** [comment]
@GOVINDDIXIT I have made a PR for the requested changes. You can review it.
