### ISSUE TITLE
Time-Table issue

### ISSUE THREAD

**Issue by Sylvester-dev** [GOVINDDIXIT/IIITL-Student-APP#212]
In landscape mode i.e. when phone is rotated then one can not scroll timetable up or down.
![TT-issue](https://user-images.githubusercontent.com/56035194/99552154-af941f80-29e2-11eb-9bb5-4aa43e80c610.jpeg)

**Comment by yk1ax** [comment]
@refactor-droidyy I've made a pr resolving this issue. You can review it.
