### ISSUE TITLE
Write a technical article on any topic in android development

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#31]
## Open for everyone

Write a technical article on any topic you have learned until now in android development.

For reference on how to write a technical article: https://android.jlelse.eu/make-android-authentication-easy-for-all-5b20820b3ee5

I will feature the best 2 articles on [DOGMA](https://worldfordevs.blogspot.com/) 🔥

First, comment here the topic you are interested in before actually start writing it

**Comment by Retarded-Ape** [comment]
I want to claim this issue

**Comment by Code414** [comment]
I wrote an article on App Widgets
