### ISSUE TITLE
Update Readme with screenshots of the app

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#37]
Update the readme of the project with the latest screenshots of the app. 
The final screenshots should look similar to [this](https://github.com/GOVINDDIXIT/IIITA-Student-App)
Use [this](https://screenshot-maker.appinstitute.com/app-screenshot-maker/editor?platform=android&layout=fullonly&out=png-1535459407&orientation=portrait) to create the screenshots

**Comment by Retarded-Ape** [comment]
i want to claim this issue!!!
