### ISSUE TITLE
Add DSC site

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#41]
Add DSC IIITL site in the navigation menu and remove "Albums"
Site Link: https://dsciiitl.netlify.com/

**Comment by Retarded-Ape** [comment]
I want to claim this issue.

**Comment by GOVINDDIXIT** [comment]
Go Ahead 👍

**Comment by GOVINDDIXIT** [comment]
@Retarded-Ape Are you working on this? The contest will end tonight

**Comment by Retarded-Ape** [comment]
Yes sir, I will submit it before midnight.

**Comment by Retarded-Ape** [comment]
Sir, "Ablums" is not currently present in the navigation drawer.
