### ISSUE TITLE
Update links and social images on DSC Site

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#42]
_**Issue is related to web development**_

**This is a pro issue which requires skills beyond your technical knowledge 😁 Open only for current top 3 performers**

**Everyone of you can work on this issue at the same time** 
First one with PR merged will get the points ⭐️ 

**Work to be done**
Update Social Links and profile images of Team members on DSC Site
DSC Website Project link: https://github.com/DSC-IIITL/DSC-IIITL-Official-Site
Site: https://dsciiitl.netlify.com/
You have to make a PR in the above project after doing all the changes.

You have to update all the social links and profile images of the team members

**For Overall lead and core members**
Add links for their LinkedIn, Github, Twitter and Facebook (You have to search the links by yourself)

**For members**
Add links for GitHub and Facebook
Take profile picture from their facebook profile

**Comment by GOVINDDIXIT** [comment]
@lav-joshi @Retarded-Ape @yk1ax Pro issue available to grab.

**Comment by yk1ax** [comment]
@GOVINDDIXIT is it open for all ? if not, then then I want to claim it

**Comment by Retarded-Ape** [comment]
I want to claim this issue.

**Comment by lav-joshi** [comment]
@GOVINDDIXIT  
updated dsc page
issue done.

**Comment by GOVINDDIXIT** [comment]
@lav-joshi lot of broken and unnecessary links are there. Request a review when it is finalized from your side.

**Comment by yk1ax** [comment]
@GOVINDDIXIT I've created a PR on the respective repo for this issue
All images added all links added and icons for the links are also properly ordered

**Comment by GOVINDDIXIT** [comment]
@lav-joshi @yk1ax 
The final verdict will be based on the following open source etiquettes 
- Amount of code change should be less and related to the actual things which are req in the issues
- Only one PR per issue is allowed, Reviewers hate to see multiple PR for the same issue. All changes should be done in the same PR.
Apart from this Adhere to the changes which are actually required by the issue. So read issue carefully
