### ISSUE TITLE
Update link for contributors

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#49]
Add contributors to this repo as the developers of the app in about us section and remove email block.

**Comment by GOVINDDIXIT** [comment]
@Retarded-Ape

**Comment by Retarded-Ape** [comment]
Am I supposed to add all the people from [this](https://github.com/GOVINDDIXIT/IIITL-Student-APP/graphs/contributors?from=2019-05-26&to=2019-12-31&type=a) page, as some in the list of the people only made a PR for #7 .

**Comment by GOVINDDIXIT** [comment]
I will deal with it later. For now just add the link to the page, people can see the contributions on their own.

**Comment by GOVINDDIXIT** [comment]
@Retarded-Ape Update?

**Comment by Retarded-Ape** [comment]
Sir, My laptop is in the store, there was a minor problem. I will fix the issue by tomorrow.
