### ISSUE TITLE
Update time table jsons

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#69]
Update time table jsons for every year and branches present [here](https://github.com/GOVINDDIXIT/IIITL-Student-APP/tree/master/app/src/main/assets/timetable) based on the new time table of even sem and previous of odd sem.

**Comment by GOVINDDIXIT** [comment]
@Retarded-Ape

**Comment by refactor-droidyy** [comment]
@Retarded-Ape  for a particular time period if there is no class scheduled include that time period and insert " " to avoid errors.

**Comment by Retarded-Ape** [comment]
> @Retarded-Ape for a particular time period if there is no class scheduled include that time period and insert " " to avoid errors.

Sure!!
