### ISSUE TITLE
setup the project locally

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#7]
### Open for everyone  
**Follow all steps to be eligible for points**
**Steps**
- Star and fork the repo
 - Setup the project locally and run the app on the emulator
- Comment with the screenshot of the same
- Make a PR adding your screenshot in the screenshot readme

**Comment by Retarded-Ape** [comment]
![Android](https://user-images.githubusercontent.com/56070571/68087922-22863300-fe80-11e9-92ca-6d17a6cff703.jpg)

**Comment by GOVINDDIXIT** [comment]
Screenshot should be of the emulator running the app (can be of splash screen 😛 )

**Comment by Retarded-Ape** [comment]
![Android](https://user-images.githubusercontent.com/56070571/68088951-20c16d00-fe8a-11e9-8831-a877ba69bbbd.jpg)

**Comment by GOVINDDIXIT** [comment]
@Retarded-Ape Make a PR adding your username and screenshot link to the [screenshot readme](https://github.com/GOVINDDIXIT/IIITL-Student-APP/tree/master/screenshots)

**Comment by shubham048** [comment]
![android](https://user-images.githubusercontent.com/54982329/68113645-41d19e80-ff1a-11e9-8e85-b06c82a0e38a.png)

**Comment by GOVINDDIXIT** [comment]
@shubham048  Make a PR adding your username and screenshot link to the [screenshot readme](https://github.com/GOVINDDIXIT/IIITL-Student-APP/tree/master/screenshots)

**Comment by Gustav619** [comment]
![Run app](https://user-images.githubusercontent.com/56060829/68115142-b528df80-ff1d-11e9-8369-6f7f069fc502.png)

**Comment by GOVINDDIXIT** [comment]
@ALL mention issues no in your PR description
partial fix: #ISSUE_NO (for issues open for all)
fix: #ISSUE_NO (other issues)

**Comment by yk1ax** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/54735451/68391801-659d1a80-018e-11ea-8f4b-dda4ed971fa5.png)

**Comment by WolverienG6** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/56384002/68392172-333fed00-018f-11ea-9981-4d9b59ecf71c.png)
