### ISSUE TITLE
Update the readme with the latest screenshots

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#78]
Update readme with the latest screenshots of the app
These screenshots may be used on the Play store to showcase the app, so check the designs of the already available apps on the play store.
For the resolution of Images required, Check [this](https://stackoverflow.com/questions/12380991/screenshot-sizes-for-publishing-android-app-on-google-play)

**Comment by GOVINDDIXIT** [comment]
@Retarded-Ape

**Comment by GOVINDDIXIT** [comment]
@Retarded-Ape Update?

**Comment by Retarded-Ape** [comment]
Sorry sir, somehow I didn't see the notification about this, I saw it just now.

Will be done before 12 today!!!!

**Comment by Retarded-Ape** [comment]
Android studio is failing to synchronize with the app again and again. I have tried it in both Linux and Windows, and in my roommate's Laptop as well.
![asas](https://user-images.githubusercontent.com/56070571/72318443-49ec4e00-36c2-11ea-9693-a30ec0d3fa40.png)

**Comment by Retarded-Ape** [comment]
The gradle build is failing again and again. I have tried it in both Windows and Linux, and in my friend's com
![asas](https://user-images.githubusercontent.com/56070571/72319208-95076080-36c4-11ea-98cf-22a77b4e96e4.png)
puter as well.

**Comment by GOVINDDIXIT** [comment]
Since we are having a proxy server now, so you have to set proxy in the android studio
