### ISSUE TITLE
create a json for all the faculty staff

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#8]
Create a JSON file containing all the details of faculty staff of IIIT Lucknow

To know more about JSON
visit [here](https://en.wikipedia.org/wiki/JSON)

The final JSON should look like [this](https://github.com/GOVINDDIXIT/IIITA-Student-App/blob/master/faculty/faculty.json)

**Comment by Retarded-Ape** [comment]
i want to fix this issue!

**Comment by shubham048** [comment]
i want to fix this issue
