### ISSUE TITLE
Add dsc credit at the end of about us page

### ISSUE THREAD

**Issue by GOVINDDIXIT** [GOVINDDIXIT/IIITL-Student-APP#82]
Remove existing dsc logo and add credit in the below given format.
Made with ❤️ by (dsc logo) and redirect to dsc website on clicking the logo.

**Comment by GOVINDDIXIT** [comment]
@refactor-droidyy

**Comment by GOVINDDIXIT** [comment]
@refactor-droidyy update?

**Comment by refactor-droidyy** [comment]
@GOVINDDIXIT sorry for being late .i will do it till noon.
