### ISSUE TITLE
Update the about page screenshot in Readme

### ISSUE THREAD

**Issue by refactor-droidyy** [GOVINDDIXIT/IIITL-Student-APP#86]

**Comment by refactor-droidyy** [comment]
@Retarded-Ape

**Comment by GOVINDDIXIT** [comment]
@Retarded-Ape Add image link of AM sir in the faculty.json

**Comment by Retarded-Ape** [comment]
I am searching for his photo from last 2-3 days, still can't find it on the internet. I will directly ask him for his pic on Monday.

**Comment by refactor-droidyy** [comment]
Checkout the E-Cell Website eventhough its not perfect but you can crop it to some scale to get the image .
